from fastapi import APIRouter, UploadFile, File, Form, HTTPException
from fastapi.responses import StreamingResponse
import pandas as pd
import io
from config import supabase
from analytics import compute_analytics

router = APIRouter()

@router.post("/upload-sales")
async def upload_sales(file: UploadFile = File(...), user_id: str = Form(...)):
    if not file.filename.endswith(".csv"):
        raise HTTPException(status_code=400, detail="Only CSV files are supported")

    try:
        contents = await file.read()

        # Try multiple encodings
        df = None
        for encoding in ["utf-8", "utf-8-sig", "latin-1", "iso-8859-1"]:
            try:
                df = pd.read_csv(io.StringIO(contents.decode(encoding)))
                break
            except Exception:
                continue

        if df is None or df.empty:
            raise HTTPException(status_code=422, detail="Could not parse CSV file")

        # Remove completely empty rows/columns
        df = df.dropna(how="all").dropna(axis=1, how="all")

        if len(df) == 0:
            raise HTTPException(status_code=422, detail="CSV file is empty")

        analytics = compute_analytics(df)
        
        # --- Clear Existing Data for User ---
        try:
             supabase.table("sales_data").delete().eq("user_id", user_id).execute()
        except Exception as e:
             print(f"Failed to clear old data for {user_id}: {e}")

        # --- Batch Insert Into Supabase ---
        # col_map = {v: k for k, v in analytics.get("columns_detected", {})}
        # Note: mapping is reverse of what compute_analytics returns. But compute_analytics returned list of matched generic types.
        # It's better simply to use the mapped column names internally generated by compute_analytics. 
        # For simplicity, we construct a normalized DB payload using the DataFrame's raw columns if detected.
        
        # Standardize DF column names
        df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_").str.replace(".", "")
        db_payload = []
        for _, row in df.iterrows():
            record = {"user_id": user_id}
            
            # Map standard columns flexibly based on content
            product_val = next((row[c] for c in ["product", "product_name", "item", "item_name", "product_id"] if c in df.columns), "Unknown Product")
            record["product"] = str(product_val) if pd.notna(product_val) else "Unknown"
            
            cat_val = next((row[c] for c in ["category", "product_category", "department", "type"] if c in df.columns), "General")
            record["category"] = str(cat_val) if pd.notna(cat_val) else "General"
            
            price_val = next((row[c] for c in ["price", "unit_price", "selling_price", "sale_price", "amount"] if c in df.columns), 0)
            record["price"] = float(price_val) if pd.notna(price_val) else 0.0

            qty_val = next((row[c] for c in ["quantity", "qty", "units", "units_sold", "quantity_sold"] if c in df.columns), 1)
            record["quantity"] = int(qty_val) if pd.notna(qty_val) else 1
            
            rev_val = next((row[c] for c in ["revenue", "total", "total_revenue", "sales_amount", "net_amount", "_revenue"] if c in df.columns), None)
            if rev_val is None:
                rev_val = record["price"] * record["quantity"]
            record["revenue"] = float(rev_val) if pd.notna(rev_val) else 0.0
            
            date_val = next((row[c] for c in ["date", "order_date", "sale_date", "transaction_date"] if c in df.columns), None)
            if date_val and pd.notna(date_val):
                try:
                    record["date"] = pd.to_datetime(date_val).isoformat()
                except:
                    pass
                    
            db_payload.append(record)
            
        # Push to SB in chunks of 500
        chunk_size = 500
        for i in range(0, len(db_payload), chunk_size):
            chunk = db_payload[i : i + chunk_size]
            res = supabase.table("sales_data").insert(chunk).execute()
            if hasattr(res, "error") and res.error:
                print(f"SUPABASE INSERT ERROR: {res.error}")

        analytics["metadata"] = {
            "filename": file.filename,
            "rows": len(df),
            "columns": df.columns.tolist(),
            "db_inserted": True
        }

        return analytics

    except HTTPException:
        raise
    except Exception as e:
        print(f"Error processing file for user {user_id}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error processing file: {str(e)}")


@router.get("/analytics")
async def get_analytics(user_id: str, range: str = "month"):
    """Returns analytics computed securely from the DB"""
    try:
        response = supabase.table("sales_data").select("*").eq("user_id", user_id).execute()
        
        data_rows = getattr(response, 'data', [])
        if not data_rows:
             return {
                 "revenue_data": [], 
                 "category_data": [],
                 "stats": {"total_revenue": "₹0", "total_orders": "0", "net_profit": "₹0", "avg_order_value": "₹0"},
                 "is_demo": False
             }

        df = pd.DataFrame(data_rows)
        
        # Apply strict date filtering based on 'range'
        if "date" in df.columns:
            df["date"] = pd.to_datetime(df["date"], errors="coerce")
            filter_date = None
            #if range == "day":
            #    filter_date = pd.Timestamp.now() - pd.Timedelta(days=1)
            #elif range == "week":
            #    filter_date = pd.Timestamp.now() - pd.Timedelta(weeks=1)
            #elif range == "month":
            #    filter_date = pd.Timestamp.now() - pd.Timedelta(days=30)
                
            if filter_date is not None:
                df = df[df["date"] >= filter_date]

        if df.empty:
             return {
        "revenue_data": [],
        "category_data": [],
        "stats": {
            "total_revenue": "₹0",
            "total_orders": "0",
            "net_profit": "₹0",
            "avg_order_value": "₹0"
        },
        "top_products": []
    }

        from fastapi.concurrency import run_in_threadpool
        return await run_in_threadpool(compute_analytics, df)

    except Exception as e:
        print(f"Error fetching DB: {str(e)}")
        raise HTTPException(status_code=500, detail="Database error or missing user_id")


@router.get("/reports/generate")
def generate_report(user_id: str, report_type: str = "Sales", format: str = "csv"):
    """Generates a downloadable file of the user's filtered data with custom naming"""
    try:
        response = supabase.table("sales_data").select("*").eq("user_id", user_id).execute()
        data_rows = getattr(response, 'data', [])
        df = pd.DataFrame(data_rows)

        if df.empty:
             raise HTTPException(status_code=400, detail="No data available for export. Please upload a CSV first.")

        if format.lower() == "pdf":
            try:
                from fpdf import FPDF
            except ImportError:
                raise HTTPException(status_code=500, detail="PDF generation library is not installed.")

            pdf = FPDF()
            pdf.add_page()
            pdf.set_font("helvetica", size=16)
            pdf.cell(0, 10, text=f"VyaaparMitra {report_type} Report", align='C')
            pdf.ln(10)
            
            pdf.set_font("helvetica", size=10)
            pdf.cell(0, 10, text=f"Total Records: {len(df)}")
            pdf.ln(10)
            
            if not df.empty:
                pdf.set_font("helvetica", 'B', 8)
                cols_to_show = df.columns[:5] # Show first 5 columns to fit
                
                # Header
                for col in cols_to_show:
                    pdf.cell(35, 10, border=1, text=str(col)[:15])
                pdf.ln()
                
                # Rows
                pdf.set_font("helvetica", '', 8)
                for _, row in df.head(50).iterrows(): # Show first 50 rows preview
                    for col in cols_to_show:
                        val = str(row[col])[:15]
                        # Encode/decode to ignore characters that break latin-1 FPDF built-in fonts
                        val = val.encode('latin-1', 'replace').decode('latin-1')
                        pdf.cell(35, 8, border=1, text=val)
                    pdf.ln()
                    
            pdf_bytes = pdf.output()
            filename = f"VyaaparMitra_{report_type.replace(' ', '_')}.pdf"
            return StreamingResponse(io.BytesIO(pdf_bytes), media_type="application/pdf", headers={"Content-Disposition": f"attachment; filename={filename}"})

        # Default CSV Fallback
        stream = io.StringIO()
        df.to_csv(stream, index=False)
        
        filename = f"VyaaparMitra_{report_type.replace(' ', '_')}_{format.upper()}.csv"
        
        res = StreamingResponse(iter([stream.getvalue()]), media_type="text/csv")
        res.headers["Content-Disposition"] = f"attachment; filename={filename}"
        return res
    except Exception as e:
        print(f"Report Generation Error: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to generate the requested report.")


