"use client";
import { getApiUrl } from "@/lib/utils";

import { motion } from "framer-motion";
import { Lightbulb, TrendingUp, Package, AlertTriangle, ArrowRight, Loader2 } from "lucide-react";
import { useState, useEffect } from "react";
import useSWR from "swr";
import { fetcher } from "@/lib/fetcher";
import { createClient } from "@/utils/supabase/client";

const ICON_MAP: Record<string, any> = {
  positive: { icon: TrendingUp, color: "text-success", bg: "bg-success/10", border: "border-success/30" },
  warning: { icon: AlertTriangle, color: "text-yellow-500", bg: "bg-yellow-500/10", border: "border-yellow-500/30" },
  negative: { icon: AlertTriangle, color: "text-red-500", bg: "bg-red-500/10", border: "border-red-500/30" },
  neutral: { icon: Lightbulb, color: "text-primary", bg: "bg-primary/10", border: "border-primary/30" },
};

export default function InsightsPage() {
  const [userId, setUserId] = useState<string | null>(null);

  useEffect(() => {
    const supabase = createClient();
    supabase.auth.getUser().then(({ data: { user } }) => {
      if (user) setUserId(user.id);
    });
  }, []);

  const { data, isLoading } = useSWR(
    userId ? `${getApiUrl()}/analytics?user_id=${userId}` : null,
    fetcher
  );
  const insights = data?.recommendations || [];

  if (isLoading) {
    return (
      <div className="h-[60vh] flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  // Ensure we have a 4th insight to fill the grid if there are exactly 3 generated ones
  const displayInsights = [...insights];
  if (displayInsights.length === 3) {
    displayInsights.push({
      type: "negative", 
      title: "Retention Opportunity",
      description: "Repeat purchases are slightly below the industry average. Implement a loyalty program to retain customers.",
      action: "Setup Loyalty Program"
    });
  }

  return (
    <div className="space-y-6">
      <div className="mb-8">
        <h2 className="text-2xl font-bold tracking-tight">AI Business Insights</h2>
        <p className="text-muted-foreground mt-2">Actionable recommendations generated by AI based on your recent sales data.</p>
      </div>

      {!displayInsights || displayInsights.length === 0 ? (
        <div className="p-12 border-2 border-dashed border-border rounded-xl text-center bg-card">
          <Lightbulb className="w-12 h-12 text-muted-foreground mx-auto mb-4 opacity-20" />
          <p className="text-muted-foreground">No insights yet. Upload a sales CSV to generate data-driven recommendations.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {displayInsights.map((insight: any, index: number) => {
            const style = ICON_MAP[insight.type] || ICON_MAP.neutral;
            const insightImages: Record<string, string> = {
              positive: "/img-pos.jpg",
              neutral: "/img-neu.jpg",
              warning: "/img-war.jpg",
              negative: "/img-neg.jpg"
            };
            const imageUrl = insightImages[insight.type] || insightImages.neutral;

            return (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className={`rounded-2xl border ${style.border} bg-card p-0 shadow-xl flex flex-col overflow-hidden hover:shadow-2xl hover:scale-[1.01] transition-all`}
              >
                <div className="relative h-40 w-full overflow-hidden">
                  <img
                    src={imageUrl}
                    alt={insight.title}
                    className="w-full h-full object-cover opacity-80"
                  />
                  <div className={`absolute bottom-4 left-4 p-3 rounded-xl ${style.bg} backdrop-blur-md shadow-lg`}>
                    <style.icon className={`w-6 h-6 ${style.color}`} />
                  </div>
                </div>

                <div className="p-6 flex flex-col flex-1">
                  <div className="flex items-start justify-between mb-2">
                    <h3 className="text-xl font-bold tracking-tight">{insight.title}</h3>
                  </div>

                  <p className="text-muted-foreground mb-6 flex-1 text-sm font-medium leading-relaxed">
                    {insight.description}
                  </p>

                  {insight.action && (
                    <div className="pt-4 border-t border-border mt-auto">
                      <p className="text-[10px] uppercase font-black tracking-widest text-muted-foreground/60 mb-3">Recommended Action</p>
                      <div className="flex items-center text-sm text-primary font-bold transition-all group cursor-pointer hover:translate-x-1">
                        {insight.action}
                        <ArrowRight className="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" />
                      </div>
                    </div>
                  )}
                </div>
              </motion.div>
            );
          })}
        </div>
      )}

      <div className="mt-8 p-6 bg-gradient-to-r from-primary/10 to-secondary/10 border border-primary/20 rounded-xl flex items-center justify-between flex-col sm:flex-row text-center sm:text-left">
        <div>
          <h3 className="text-lg font-semibold mb-1">Need more specific advice?</h3>
          <p className="text-muted-foreground text-sm">Ask the AI Assistant questions about your business data.</p>
        </div>
        <button
          onClick={() => window.location.href = "/assistant"}
          className="mt-4 sm:mt-0 px-6 py-2 bg-primary text-primary-foreground rounded-lg font-medium hover:bg-primary/90 transition-colors"
        >
          Open AI Assistant
        </button>
      </div>
    </div>
  );
}
